### ISSUE TITLE
Error running the tutorial example

### ISSUE THREAD

**Issue by rubenlucas93** [JdeRobot/DetectionStudio#208] opened 2020-11-28 11:48 UTC
Hi, I already followed all the steps mentioned in the tutorial but I got the following issues:

1. When running detectionStudio with permissions granted with  "sudo chmod -R 666 /opt/datasets" I got this error:
![permissionsError](https://user-images.githubusercontent.com/10724346/100514748-88beb180-3177-11eb-86e5-0c38aab9e099.PNG)

2. Once I solved this error giving permissions to all with "sudo chmod -R 777 /opt/datasets" and after configuring the folders and files as indicated I got the following error when clicking in "Select Input".
![image](https://user-images.githubusercontent.com/10724346/100514802-e6eb9480-3177-11eb-87ec-1a4e267d1368.png)

![image](https://user-images.githubusercontent.com/10724346/100514816-f965ce00-3177-11eb-8e14-a0646d1b91b5.png)

I also get this warning when launching the app. It may help:
![image](https://user-images.githubusercontent.com/10724346/100514825-0e426180-3178-11eb-82cd-165edcab0e21.png)

Thanks in advance!

**Comment by sergiopaniego** [comment] 2020-12-01 16:21
Hi! Thanks for the report and for using our tool! 

Could you be us some more details about your deployment? Are you using Detection Studio installed fromm source code or the docker images with everything built-in?

**Comment by rubenlucas93** [comment] 2020-12-01 16:43
I installed it from source code.

It may be irrelevant but when building Detection Studio I had another issue:
Detection studio was looking for the opencv2/opencv.hpp file in /usr/include folder, but when executing "sudo apt-get install python-opencv" this file was generated in /usr/include/opencv4/opencv2/opencv.hpp so I had to move it to the expected location to make it work.

**Comment by sergiopaniego** [comment] 2020-12-02 17:13
When clicking *Select Input*, a pop up window should appear asking you to select a file from the path where you are executing the application. 
I'd suggest you to check for permissions for ./DatasetEvaluationApp and the path that it access. 
Could you try with *sudo*?

**Comment by rubenlucas93** [comment] 2020-12-03 12:03
Great. It was solved running DatasetEvaluationApp with sudo.

Now when I click in "Process" with this 

![image](https://user-images.githubusercontent.com/10724346/101015515-d49e9b80-3567-11eb-814c-2d2654b472b1.png)


The window closes and I get the following error:

![image](https://user-images.githubusercontent.com/10724346/101015619-f7c94b00-3567-11eb-80ea-278df8ff6df6.png)

Do you want me to create a different issue for this??

Thanks!
Best regards,
Rubén.

**Comment by sergiopaniego** [comment] 2020-12-03 16:52
It says no module named numpy... Have you installed numpy?
I have checked and it's not in the requirements. Could be a issue. 
Please check installing numpy and if you manage to run it we should add that requirement.

**Comment by rubenlucas93** [comment] 2020-12-13 10:44
Hi, I tried the following:
uninstalling and installing numpy
uninstalling and installing tensorflow
uncomment some #includes in TensorFlowInferencer.h

but none of this worked.
When I import this module directly in python3 it works and, in fact, I see the module in numpy lib folder

![image](https://user-images.githubusercontent.com/10724346/102009475-e9cdb400-3d37-11eb-98ef-df5ee9e31bd7.png)

I tried to recompile several times and I get a warning about numpy, but after googling, it should not to be a problem:
![image](https://user-images.githubusercontent.com/10724346/102009518-2d282280-3d38-11eb-8315-6f7bd3cf8511.png)

I will try to install DetectionStudio via docker now but if you have any suggestion or question to solve this problem I would appreciate it.

Thanks!
Regards,
Rubén.

**Comment by rubenlucas93** [comment] 2020-12-13 11:26
Hi again!
Trying to install it  via docker.

I ran the command indicated in the install tutorial: 
docker run -dit --name detection-studio -v [local_directory]:/root/volume/ -e DISPLAY=host.docker.internal:0 jderobot/detection-studio:latest

It created a container but no gui is displayed.
I tried to start the container but it does nothing and, when I type "docker ps" I don´t see any container running.

I showed here the executed commands and the result (note that the last one is just for letting you know how I installed the docker):

![image](https://user-images.githubusercontent.com/10724346/102010456-6d8a9f00-3d3e-11eb-8cfb-e077b3bccb37.png)


Thanks,
Best regards,
Rubén.

**Comment by sergiopaniego** [comment] 2020-12-14 12:55
Answers for both questions:


1. The module that runs tensorflow and numpy etc is [tensoflow_detect.py](https://github.com/JdeRobot/DetectionStudio/blob/master/DetectionStudio/DetectionStudioLib/python_modules/tensorflow_detect.py). That file creates the detection graph and runs inferences over the images. Could you try running isolated that file inferencing one random image to understand where the problem is coming from?

2. Could you provide logs from docker? `docker logs [container_name]`? That docker container is suppose to open a window when run. Could be something related to DISPLAY variable. It opens a qt5 window. 
Dockerfile source is [here](https://github.com/JdeRobot/DetectionStudio/blob/master/DetectionStudio/Dockerfile/Dockerfile) if you want to take a look.

**Comment by rubenlucas93** [comment] 2020-12-17 14:54
Hi again,

1. I had a different problem with my environment and I had to install it all from scratch. After repeating the libraries and different tools installations, I got to reach a different error (This time DetectionStudio does not closes):

![image](https://user-images.githubusercontent.com/10724346/102503559-207d3480-4080-11eb-905a-971391dd5105.png)

![image](https://user-images.githubusercontent.com/10724346/102503419-004d7580-4080-11eb-903c-b58d53a52978.png)

2. This is the log displayed:
![image](https://user-images.githubusercontent.com/10724346/102503230-c9775f80-407f-11eb-8098-89baafff6ee6.p


I will take another look tomorrow, but today I did not got to solve it.

Thanks a lot for your support!

**Comment by sergiopaniego** [comment] 2020-12-17 18:48
1. The first error says that it can't open the video file. Could you try with another video file?


2. The docker error is related with the X display. This error tells you that docker can't display the screen because it can't connect to it.  You could try opening a new terminal and do:

`socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"`

and the run the application.

**Comment by rubenlucas93** [comment] 2020-12-19 10:11
Hi again!

1. I tried with 3 videos and none of them is working. However the first video should work, since I read in another issue for detection studio that one of the maintainers suggested to use exactly that one.

2. It didn´t work either. I am trying now different solutions provided in stackoverflow but they seem to not to help so far.

**Comment by rubenlucas93** [comment] 2020-12-20 13:00
Hi again.

1. I  got to see that the TensorflowInferencer.cpp didn´t get the same sys.path as the one I have in my environment.
I manually add the path '/home/rlucasz/.local/libs/python2.7/site-packages and now it found numpy. Now the problem is that it still doesn´t find some other components related to tensorflow as "tools". I will try to figure it out and let you know how it goes.

2. Still not working

**Comment by rubenlucas93** [comment] 2020-12-21 20:57
Hi!!!:

   1. The problem is that, when running DataEvaluationApp with sudo, the paths and permissions are different and, for whatever reason, there are some libraries not found (e.g tensorflow.python.tools or google) giving exception after exception.

Could you help me to run this without sudo??? The problem was the first reported. Do you know the paths accesed by DataEvaluationApp???

Thanks in advance.

**Comment by rubenlucas93** [comment] 2020-12-21 21:21
Hi!!

1. FIXED FINALLY!!!
For whatever reason those two lines where not working other than as a sudo.
I commented them and it is working now.
![image](https://user-images.githubusercontent.com/10724346/102823280-ec38a980-43da-11eb-8167-442453d25fed.png)

Sorry for the insistence.

Thanks!!
Best regards and merry christmas!
Rubén.

**Comment by sergiopaniego** [comment] 2020-12-23 10:49
Could you sum up the problematic and the solution, please?
It could be interesting updating the code/installation instructions with the solution if we find it necessary. 
Do you feel something in the instructions is not clear enough? If so, you can open an issue and PR with the content updated.

**Comment by rubenlucas93** [comment] 2020-12-24 13:07
I just let you know in here so you can update it if you consider it needed.

Finally, to install and make detectionStudio work in my Ubuntu 20.04.1 LTS, the provided manual and the following two actions are enough:

1. Install some libraries needed by opencv to work with some images and video formats:
sudo apt-get install libjpeg8-dev libtiff5-dev libjasper-dev libpng12-dev
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
sudo apt-get install libxvidcore-dev libx264-dev

2. After downloading opencv and creating the build directory inside, the cmake must be executed with the following flags:
make -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_C_EXAMPLES=ON  -D INSTALL_PYTHON_EXAMPLES=ON  -D BUILD_EXAMPLES=ON  -D BUILD_opencv_python2=ON  -D WITH_FFMPEG=1  -D WITH_CUDA=ON  -D CUDA_GENERATION=Pascal -D ENABLE_FAST_MATH=1  -D CUDA_FAST_MATH=1 -D WITH_CUBLAS=1   ..

![image](https://user-images.githubusercontent.com/10724346/103089490-5b3a1c00-45ee-11eb-8fe3-3fc982180841.png)

And then check that the following options are displayed as "YES":

![image](https://user-images.githubusercontent.com/10724346/103090439-490dad00-45f1-11eb-96f1-c9be786d63f3.png)

3. In my case the following patch was applied to be able to choose a video to be evaluated, but I am not sure whether this is a matter of my installed qt version or if it is actually an error.
Anyway, just in case you want to consider, I leave here the applied patch in path "DetectionStudio/DetectionStudio/DatasetEvaluationApp/mainwindow.cpp".

[mainwindow_patch.txt](https://github.com/JdeRobot/DetectionStudio/files/5739608/mainwindow_patch.txt)

**Comment by jmplaza** [comment] 2020-12-24 13:10
Hi @rubenlucas93, feel free to create and submit a pull-request with those improvements, regarding this issue. We will review it and eventually merge it into the master branch of the project.

**Comment by rubenlucas93** [comment] 2020-12-25 10:29
I was about to create a branch, push my changes to that branch and then create a pull request from there, but it was not possible due to lack of permissions:
![image](https://user-images.githubusercontent.com/10724346/103132262-44ee9780-46a4-11eb-8de2-677f8f24f89a.png)

Could you grant me grant me those so I can do it?

Thanks!
Regards.

**Comment by jmplaza** [comment] 2020-12-25 14:14
Hi @rubenlucas93 , you don't need write access on the repository to create a pull-request to it. Please learn how to do it, for instance: [https://gist.github.com/dlaehnemann/e6c8f46eee80112267af70ae92a3df13](https://gist.github.com/dlaehnemann/e6c8f46eee80112267af70ae92a3df13) and [https://stackoverflow.com/questions/2916845/different-default-remote-tracking-branch-for-git-pull-and-git-push/30488025#30488025](https://stackoverflow.com/questions/2916845/different-default-remote-tracking-branch-for-git-pull-and-git-push/30488025#30488025)

**Comment by rubenlucas93** [comment] 2020-12-25 19:47
Right!!!

Learned and done!

Thanks!
Regards,
Rubén.

**Comment by sergiopaniego** [comment] 2020-12-27 16:14
Merged! Closing the issue.

Thanks for your first contribution! 😄

**Closed by sergiopaniego** 2020-12-27 16:14 UTC
